project:
  type: website
  render:
    - "*.qmd"
    - "!static/"
  post-render:
    # - "mkdir _site/static"
    # - "cp -rnv static/. _site/static/."
    - echo 'declaredesign.org' > _site/CNAME


website:
  title: "**Declare**Design"
  navbar:
    logo: static/dd-logo-sm.svg
    right:
      - text: "Getting started"
        href: getting-started/
      - text: Book
        href: https://book.declaredesign.org
      - text: Software
        menu: 
          - text: DeclareDesign
            href: /r/declaredesign/
          - text: fabricatr
            href: /r/fabricatr/
          - text: randomizr
            href: /r/randomizr/
          - text: estimatr
            href: /r/estimatr/
          - text: rdss 
            href: /r/rdss/
          - text: DesignLibrary
            href: /r/designlibrary/
          - text: DesignWizard
            href: https://eos.wzb.eu/ipi/DDWizard/
      - text: Blog
        href: /blog/
      - text: About
        href: /about/

format:
  html:
    theme: [cosmo, theme.scss]
    css: styles.css



