on:
  schedule:
    - cron: 0 0 * * 6 # run weekly
  repository_dispatch: # run manually
    types: [check-link]
  push:
    branches:
      - gh-pages

name: Broken Link Check
jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Broken Link Check
        uses: technote-space/broken-link-checker-action@v2