---
title: "What is MIDA?"
title-block-banner: true
---

<font size="6">MIDA are the four components of a research design</font>

Research designs share in common that they all have an inquiry *I*, a data strategy *D*, and an answer strategy *A*. Less obviously, perhaps, these three elements presuppose a model *M* of how the world works. We refer to the four together as *MIDA*. 

We think of *MIDA* as having two sides. *M* and *I* form the theoretical half, comprising your beliefs about the world and your target of inference. *D* and *A* form the empirical half, comprising your strategies for collecting and summarizing information. The theoretical side sets the research challenges for you to overcome and the empirical side captures your responses to those challenges.

The set of models in *M* comprises speculations about what causes what and how. It includes guesses about how important variables are generated, how they are correlated, and the sequences of events. 

The inquiry *I* is a research question stated in terms of the model. For example, the inquiry might be the average causal effect of one variable on another, the descriptive distribution of a third variable, or a prediction about the value of a variable in the future. We refer to "the" inquiry when talking about the main research question, but in practice we may seek to learn about many inquiries in a single research study. 

The data strategy *D* is the full set of procedures we use to gather information from the world. The three basic elements of data strategies parallel the three features of inquiries: *units* are selected, *conditions* are assigned, and *outcomes* are measured. 

The answer strategy *A* is what we use to summarize the data produced by the data strategy. Just like the inquiry summarizes a part of the model, the answer strategy summarizes a part of the data. We can't just "let the data speak" because complex, multidimensional datasets don't speak for themselves---they need to be summarized and explained. Answer strategies are the procedures we follow to do so.

For more, read [Chapter 2 of the book](https://book.declaredesign.org/introduction/what-is-a-research-design.html).