---
title: "About DeclareDesign"
title-block-banner: true
about:
  template: marquee
---

The DeclareDesign project was founded by [Graeme Blair](https://graemeblair.com) (UCLA), [Jasper Cooper](http://jasper-cooper.com) (Office of Evaluation Sciences, US General Services Administration), [Alexander Coppock](http://alexandercoppock.com) (Yale University), and [Macartan Humphreys](https://macartan.github.io/) (WZB Berlin).

## Publications

Blair, Graeme, Jasper Cooper, Alexander Coppock, and Macartan Humphreys. "Declaring and diagnosing research designs." *American Political Science Review* 113, no. 3 (2019): 838-859. [pdf](/paper.pdf) [bibtex](/paper_cite.txt)

Blair, Graeme, Alexander Coppock, and Macartan Humphreys. "Research Design in the Social Sciences: Declaration, Diagnosis, and Redesign." Princeton University Press (2023). [amazon](https://www.amazon.com/Research-Design-Social-Sciences-Declaration/dp/0691199574/?&_encoding=UTF8&tag=declaredesign-20&linkCode=ur2&linkId=84be1f952d1d7aaaa5be867eade93474&camp=1789&creative=9325) [press](https://press.princeton.edu/books/paperback/9780691199573/research-design-in-the-social-sciences) [free online](https://book.declaredesign.org) [bibtex](/book_cite.txt)

## Contributors

DeclareDesign has benefited from the contributions of many researchers and coders. We recognize key contributors in addition to the principal investigators to each component:

`DeclareDesign` for R: Neal Fultz

`estimatr` for R: [Luke Sonnet](http://lukesonnet.com)

`fabricatr` for R: [Aaron Rudkin](http://rudkin.ca)

`randomizr` for Stata: [John Ternovski](http://www.jter.co)

`DeclareDesignWizard`: [Clara Bicalho](https://clarabicalho.github.io/), [Markus Konrad](https://twitter.com/_knrd), and [Sisi Huang](https://twitter.com/zerinahuang)

`DesignLibrary`: [Clara Bicalho](https://clarabicalho.github.io/) and [Lily Medina](https://lilymedina.github.io/)

`declaredesign.org`: Nicholas Rivera

We thank contributors to earlier iterations of the project Thomas Leavitt, Tara Slough, Georgiy Syunyaev, and Anna Wilke. We also thank early beta testers Lauren Young, Erin York, and Yang-Yang Zhou.

## Support

We encourage you to submit bug reports and feature requests for our software as [Github](https://github.com/DeclareDesign) issues.

## Funding

We are grateful for major funding from the [Laura and John Arnold Foundation](http://www.arnoldfoundation.org/)
and seed funding from [EGAP -- Evidence in Governance and Politics](http://egap.org).

